estimators:
  - name: Linear-Regression
    class_name: sklearn.linear_model.LinearRegression
    linear: true
    parameters:
      estimator__fit_intercept: [True] # TODO for now need to have at least one candidate for parameter search
  - name: Ridge-Regression
    class_name: sklearn.linear_model.Ridge
    linear: true
    parameters:
      estimator__alpha: [0.001, 0.01, 0.1, 1.0]
  - name: ElasticNet-Regression
    class_name: sklearn.linear_model.ElasticNet
    linear: true
    parameters:
      estimator__alpha: [1.0]
      estimator__l1_ratio: [0.3]
      estimator__max_iter: [1000]
      estimator__selection: ['random']
  - name: XGBoost-Regressor
    class_name: xgboost.XGBRegressor
    linear: false
    parameters:
      estimator__max_depth: [3, 6]
      estimator__eta: [0.01, 0.3]
      estimator__subsample: [0.5, 1.0]
      estimator__gamma: [0.0, 0.1] 



