estimators:
  - name: CatBoost-Regressor
    class_name: catboost.CatBoostRegressor
    linear: false
    parameters:
      estimator__learning_rate: [ 1e-3, 0.1 ]
      estimator__depth: [ 6, 8 ]
      estimator__colsample_bylevel: [ 0.05, 0.5, 1.0 ]
      estimator__min_data_in_leaf: [ 1, 50, 100 ]





