loglevel: DEBUG
job:
  job_spec_file: "../examples/MLCommons/job_spec.yaml"
actuation_templates:
  analyze-jobs: >
    pip install -q -r ../requirements.txt;
    python ../src/main.py analyze-jobs --input-path ../examples/MLCommons 
    --job-spec-file-name job_spec.yaml
  auto-build-models: > 
    pip install -q -r ../requirements.txt;
    python ../src/main.py auto-build-models --input-path ../examples/MLCommons 
    --config-file ../config/small-auto-model-search-config.yaml
  predict: >
    pip install -q -r ../requirements.txt;
    python ../src/main.py predict --input-path ../examples/MLCommons 
    --model-path ../examples/MLCommons/ARISE-auto-models 
    --config-file ../config/example-demo-mlcommons-config.yaml

