loglevel: DEBUG
job:
  job_spec_file: "../examples/MLCommons/job_spec.yaml"
  input_path: "../examples/MLCommons"
  python: "python"
  executable: "../src/main.py"
  model_path: "../examples/MLCommons/ARISE-auto-models"
  prediction:
    config_file: "../config/generated-prediction-config-file.yaml"
    estimator_file: "estimator-nonlinear-XGBoost-Regressor-tokens_per_second.pkl"
    greater_is_better: True
actuation_templates:
  analyze-jobs: >
    pip install -q -r ../requirements.txt;
    $python $executable analyze-jobs --input-path $input_path 
    --job-spec-file-name job_spec.yaml
  auto-build-models: > 
    pip install -q -r ../requirements.txt;
    $python $executable auto-build-models --input-path $input_path 
    --config-file ../config/small-auto-model-search-config.yaml
  predict: >
    pip install -q -r ../requirements.txt;
    $python $executable predict --input-path $input_path 
    --model-path $model_path 
    --config-file $prediction_config_file
  demo-predict: >
    pip install -q -r ../requirements.txt;
    $python $executable demo-predict --input-path $input_path 
    --model-path $model_path 
    --config-file $prediction_config_file
